; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define SourcePath "\\?\Volume{cc498e86-0000-0000-0000-602200000000}\Users\jason\Desktop\coh_npc_voices"
#define MyAppName "Sidekick"
#define MyAppVersion "3.1"
#define MyAppPublisher "Jason Kane"
#define MyAppURL "https://github.com/jason-kane/coh_npc_voices"
#define MyAppExeName "Sidekick.bat"
#define MyAppIcon "sidekick.ico"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)

AppId={{7F6AB435-BCD4-46D2-AA07-EE65EAF992FA}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\COH Sidekick
DisableProgramGroupPage=yes
LicenseFile=C:\Users\jason\Desktop\coh_npc_voices\LICENSE
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputBaseFilename=sidekick_setup
Compression=zip
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#SourcePath}\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourcePath}\aliases.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourcePath}\all_npcs.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourcePath}\config.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourcePath}\sidekick.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourcePath}\requirements.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourcePath}\win_install.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourcePath}\cnv\__init__.py"; DestDir: "{app}\cnv\"; Flags: ignoreversion 
Source: "{#SourcePath}\cnv\chatlog\__init__.py"; DestDir: "{app}\cnv\chatlog\"; Flags: ignoreversion 
Source: "{#SourcePath}\cnv\chatlog\npc_chatter.py"; DestDir: "{app}\cnv\chatlog\"; Flags: ignoreversion 
Source: "{#SourcePath}\cnv\database\__init__.py"; DestDir: "{app}\cnv\database\"; Flags: ignoreversion 
Source: "{#SourcePath}\cnv\database\db.py"; DestDir: "{app}\cnv\database\"; Flags: ignoreversion 
Source: "{#SourcePath}\cnv\database\models.py"; DestDir: "{app}\cnv\database\"; Flags: ignoreversion 
Source: "{#SourcePath}\cnv\effects\__init__.py"; DestDir: "{app}\cnv\effects\"; Flags: ignoreversion 
Source: "{#SourcePath}\cnv\effects\effects.py"; DestDir: "{app}\cnv\effects\"; Flags: ignoreversion 
Source: "{#SourcePath}\cnv\engines\__init__.py"; DestDir: "{app}\cnv\engines\"; Flags: ignoreversion 
Source: "{#SourcePath}\cnv\engines\amazonpolly.py"; DestDir: "{app}\cnv\engines\"; Flags: ignoreversion 
Source: "{#SourcePath}\cnv\engines\azure.py"; DestDir: "{app}\cnv\engines\"; Flags: ignoreversion 
Source: "{#SourcePath}\cnv\engines\base.py"; DestDir: "{app}\cnv\engines\"; Flags: ignoreversion 
Source: "{#SourcePath}\cnv\engines\elevenlabs.py"; DestDir: "{app}\cnv\engines\"; Flags: ignoreversion 
Source: "{#SourcePath}\cnv\engines\engines.py"; DestDir: "{app}\cnv\engines\"; Flags: ignoreversion 
Source: "{#SourcePath}\cnv\engines\googlecloud.py"; DestDir: "{app}\cnv\engines\"; Flags: ignoreversion 
Source: "{#SourcePath}\cnv\engines\openai.py"; DestDir: "{app}\cnv\engines\"; Flags: ignoreversion 
Source: "{#SourcePath}\cnv\engines\windowstts.py"; DestDir: "{app}\cnv\engines\"; Flags: ignoreversion 
Source: "{#SourcePath}\cnv\lib\icons\*.png"; DestDir: "{app}\cnv\lib\icons"; Flags: ignoreversion 
Source: "{#SourcePath}\cnv\lib\__init__.py"; DestDir: "{app}\cnv\lib\"; Flags: ignoreversion 
Source: "{#SourcePath}\cnv\lib\audio.py"; DestDir: "{app}\cnv\lib\"; Flags: ignoreversion 
Source: "{#SourcePath}\cnv\lib\gui.py"; DestDir: "{app}\cnv\lib\"; Flags: ignoreversion 
Source: "{#SourcePath}\cnv\lib\proc.py"; DestDir: "{app}\cnv\lib\"; Flags: ignoreversion 
Source: "{#SourcePath}\cnv\lib\settings.py"; DestDir: "{app}\cnv\lib\"; Flags: ignoreversion 
Source: "{#SourcePath}\cnv\tabs\__init__.py"; DestDir: "{app}\cnv\tabs\"; Flags: ignoreversion 
Source: "{#SourcePath}\cnv\tabs\automation.py"; DestDir: "{app}\cnv\tabs\"; Flags: ignoreversion 
Source: "{#SourcePath}\cnv\tabs\character.py"; DestDir: "{app}\cnv\tabs\"; Flags: ignoreversion 
Source: "{#SourcePath}\cnv\tabs\configuration.py"; DestDir: "{app}\cnv\tabs\"; Flags: ignoreversion 
Source: "{#SourcePath}\cnv\tabs\voices.py"; DestDir: "{app}\cnv\tabs\"; Flags: ignoreversion 
Source: "{#SourcePath}\cnv\voices\__init__.py"; DestDir: "{app}\cnv\voices\"; Flags: ignoreversion 
Source: "{#SourcePath}\cnv\voices\generate_defaults.py"; DestDir: "{app}\cnv\voices\"; Flags: ignoreversion 
Source: "{#SourcePath}\cnv\voices\voice_builder.py"; DestDir: "{app}\cnv\voices\"; Flags: ignoreversion 
Source: "{#SourcePath}\cnv\voices\voice_editor.py"; DestDir: "{app}\cnv\voices\"; Flags: ignoreversion 
Source: "{#SourcePath}\cnv\__init__.py"; DestDir: "{app}\cnv\"; Flags: ignoreversion 
Source: "{#SourcePath}\cnv\alembic.ini"; DestDir: "{app}\cnv\"; Flags: ignoreversion 
Source: "{#SourcePath}\cnv\logger.py"; DestDir: "{app}\cnv\"; Flags: ignoreversion 
Source: "{#SourcePath}\cnv\sidekick.py"; DestDir: "{app}\cnv\"; Flags: ignoreversion 
Source: "{#SourcePath}\aliases.json"; DestDir: "{app}\"; Flags: ignoreversion 
Source: "{#SourcePath}\all_npcs.json"; DestDir: "{app}\"; Flags: ignoreversion 
Source: "{#SourcePath}\migrations\*"; DestDir: "{app}\migrations\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#SourcePath}\venv\*"; DestDir: "{app}\venv"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{userdesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\{#MyAppIcon}"; Tasks: desktopicon

[Run]
Filename: "{app}\win_install.exe"; StatusMsg: "Installing Dependencies...."
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

