"""empty message

Revision ID: 0e2640a2c350
Revises: c1f376474050
Create Date: 2024-06-29 10:01:46.832778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e2640a2c350'
down_revision: Union[str, None] = 'c1f376474050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translations', sa.Column('text', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translations', 'text')
    # ### end Alembic commands ###
