"""empty message

Revision ID: 56704d360a85
Revises: 
Create Date: 2024-06-27 17:54:57.597348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56704d360a85'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('engine', sa.String(length=64), nullable=False),
    sa.Column('engine_secondary', sa.String(length=64), nullable=False),
    sa.Column('category', sa.Integer(), nullable=False),
    sa.Column('last_spoke', sa.DateTime(), nullable=True),
    sa.Column('group_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_category'), 'character', ['category'], unique=False)
    op.create_table('eleven_labs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('voice_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engine_config_meta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('engine_key', sa.String(length=64), nullable=False),
    sa.Column('cosmetic', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('varfunc', sa.String(length=64), nullable=False),
    sa.Column('default', sa.String(length=64), nullable=False),
    sa.Column('cfgdict', sa.JSON(), nullable=False),
    sa.Column('gatherfunc', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('google_voices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('language_code', sa.String(length=64), nullable=False),
    sa.Column('ssml_gender', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hero',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('logdir', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('base_tts_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('effects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('effect_name', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hero_stat_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('xp_gain', sa.Integer(), nullable=True),
    sa.Column('inf_gain', sa.Integer(), nullable=True),
    sa.Column('hero_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hero_id'], ['hero.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phrases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=256), nullable=False),
    sa.Column('ssml', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('effect_setting',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('effect_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['effect_id'], ['effects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('effect_setting')
    op.drop_table('phrases')
    op.drop_table('hero_stat_events')
    op.drop_table('effects')
    op.drop_table('base_tts_config')
    op.drop_table('settings')
    op.drop_table('hero')
    op.drop_table('google_voices')
    op.drop_table('engine_config_meta')
    op.drop_table('eleven_labs')
    op.drop_index(op.f('ix_character_category'), table_name='character')
    op.drop_table('character')
    # ### end Alembic commands ###
