"""add damage table

Revision ID: 937d6b648884
Revises: 0e2640a2c350
Create Date: 2024-07-27 08:59:17.566328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '937d6b648884'
down_revision: Union[str, None] = '0e2640a2c350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('damage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hero_id', sa.Integer(), nullable=True),
    sa.Column('target', sa.String(length=256), nullable=False),
    sa.Column('power', sa.String(length=256), nullable=False),
    sa.Column('damage', sa.Integer(), nullable=False),
    sa.Column('damage_type', sa.String(length=64), nullable=False),
    sa.Column('special', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['hero_id'], ['hero.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('damage')
    # ### end Alembic commands ###
