"""empty message

Revision ID: c1f376474050
Revises: 56704d360a85
Create Date: 2024-06-28 22:37:17.424695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1f376474050'
down_revision: Union[str, None] = '56704d360a85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phrase_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['phrase_id'], ['phrases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('settings')
    op.drop_column('phrases', 'ssml')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phrases', sa.Column('ssml', sa.VARCHAR(length=512), nullable=False))
    op.create_table('settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('logdir', sa.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('translations')
    # ### end Alembic commands ###
